# -*- coding: utf-8 -*-
# This file was *autogenerated* from the file test.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0)
from megua.all import *
meg = MegBook('amc.sqlite')

meg.getexercise("E97G40_produto_escalar2_R2_008", ekey=_sage_const_10 )

print "Problem"
print meg.getproblem()
print "Answer"
print meg.getproblem()
print "Corret choice"
print meg.getoption(_sage_const_0 )
print "Wrong choice 1"
print meg.getoption(_sage_const_1 )
print "Wrong choice 2"
print meg.getoption(_sage_const_2 )
print "Wrong choice 3"
print meg.getoption(_sage_const_3 )
