#!/usr/bin/env bash

SAGECMD="/home/jpedro/SageMath/sage"
MEGUAROOT="/home/jpedro/megua/megua"

$SAGECMD -python $MEGUAROOT/c_megua.py "$@"

exit



######################################################
#### THIS, below, IS DONE IN PYTHON IN c_megua.py ####
######################################################


SAGECMD="/home/jpedro/Downloads/SageMath/sage"
MEGUAROOT="/home/jpedro/megua/megua"

usage() {
    ####  1.......................26..................................................78
    ####  |.....................--.|...................................................|
    echo "Arguments:"
    echo "  help <cmd>          -- calls help on command <cmd>"  
    echo "  catalog             -- produce a catalog based on exercises database"  
    echo "  dup                 -- duplicate name, inc. counter, make new exercise file"  
    echo "  new                 -- make new exercise file"  
    echo "  meg2smc             -- convert megua5.2 database to megua for smc"  
}


help() {

    if [ "$1" = "meg2smc" ]; then
        echo "Calling sagemath (wait..)"
        $SAGECMD -python $MEGUAROOT/meg2smc.py help
        exit
    fi

    echo "Arguments:"
    echo "  help <cmd>          -- calls help on command <cmd>"  
}

catalog() {


sage -python $MEGUAROOT/catalog.py
pdflatex --nonstop /catalog.tex


}


if [ "$1" = "help" ]; then
    help $2 
    exit 
fi

#otherwise, display usage calling usage function
usage

